/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as onboardingRouteRouteImport } from './routes/(onboarding)/route'
import { Route as authForgottenPasswordRouteImport } from './routes/(auth)/forgotten-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authTwoFactorRouteImport } from './routes/(auth)/two-factor'
import { Route as authenticatedAccountsRouteImport } from './routes/(authenticated)/accounts'
import { Route as authenticatedCategoriesRouteImport } from './routes/(authenticated)/categories'
import { Route as authenticatedDashboardRouteImport } from './routes/(authenticated)/dashboard'
import { Route as authenticatedOrganizationRouteImport } from './routes/(authenticated)/organization'
import { Route as authenticatedSettingsRouteImport } from './routes/(authenticated)/settings'
import { Route as authenticatedTransactionsRouteImport } from './routes/(authenticated)/transactions'
import { Route as onboardingAcceptInvitationRouteImport } from './routes/(onboarding)/accept-invitation'
import { Route as onboardingOnboardingRouteImport } from './routes/(onboarding)/onboarding'
import { Route as authenticatedCreditCardsAccountIdRouteImport } from './routes/(authenticated)/credit-cards.$accountId'
import { Route as onboardingOnboardingSetupRouteImport } from './routes/(onboarding)/onboarding.setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const onboardingRouteRoute = onboardingRouteRouteImport.update({
  id: '/(onboarding)',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgottenPasswordRoute = authForgottenPasswordRouteImport.update({
  id: '/forgotten-password',
  path: '/forgotten-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authTwoFactorRoute = authTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => authRouteRoute,
} as any)
const authenticatedAccountsRoute = authenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedCategoriesRoute = authenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedDashboardRoute = authenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedOrganizationRoute =
  authenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSettingsRoute = authenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedTransactionsRoute =
  authenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const onboardingAcceptInvitationRoute =
  onboardingAcceptInvitationRouteImport.update({
    id: '/accept-invitation',
    path: '/accept-invitation',
    getParentRoute: () => onboardingRouteRoute,
  } as any)
const onboardingOnboardingRoute = onboardingOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => onboardingRouteRoute,
} as any)
const authenticatedCreditCardsAccountIdRoute =
  authenticatedCreditCardsAccountIdRouteImport.update({
    id: '/credit-cards/$accountId',
    path: '/credit-cards/$accountId',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const onboardingOnboardingSetupRoute =
  onboardingOnboardingSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => onboardingOnboardingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgotten-password': typeof authForgottenPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-up': typeof authSignUpRoute
  '/two-factor': typeof authTwoFactorRoute
  '/accounts': typeof authenticatedAccountsRoute
  '/categories': typeof authenticatedCategoriesRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/organization': typeof authenticatedOrganizationRoute
  '/settings': typeof authenticatedSettingsRoute
  '/transactions': typeof authenticatedTransactionsRoute
  '/accept-invitation': typeof onboardingAcceptInvitationRoute
  '/onboarding': typeof onboardingOnboardingRouteWithChildren
  '/credit-cards/$accountId': typeof authenticatedCreditCardsAccountIdRoute
  '/onboarding/setup': typeof onboardingOnboardingSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgotten-password': typeof authForgottenPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-up': typeof authSignUpRoute
  '/two-factor': typeof authTwoFactorRoute
  '/accounts': typeof authenticatedAccountsRoute
  '/categories': typeof authenticatedCategoriesRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/organization': typeof authenticatedOrganizationRoute
  '/settings': typeof authenticatedSettingsRoute
  '/transactions': typeof authenticatedTransactionsRoute
  '/accept-invitation': typeof onboardingAcceptInvitationRoute
  '/onboarding': typeof onboardingOnboardingRouteWithChildren
  '/credit-cards/$accountId': typeof authenticatedCreditCardsAccountIdRoute
  '/onboarding/setup': typeof onboardingOnboardingSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(onboarding)': typeof onboardingRouteRouteWithChildren
  '/(auth)/forgotten-password': typeof authForgottenPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/two-factor': typeof authTwoFactorRoute
  '/(authenticated)/accounts': typeof authenticatedAccountsRoute
  '/(authenticated)/categories': typeof authenticatedCategoriesRoute
  '/(authenticated)/dashboard': typeof authenticatedDashboardRoute
  '/(authenticated)/organization': typeof authenticatedOrganizationRoute
  '/(authenticated)/settings': typeof authenticatedSettingsRoute
  '/(authenticated)/transactions': typeof authenticatedTransactionsRoute
  '/(onboarding)/accept-invitation': typeof onboardingAcceptInvitationRoute
  '/(onboarding)/onboarding': typeof onboardingOnboardingRouteWithChildren
  '/(authenticated)/credit-cards/$accountId': typeof authenticatedCreditCardsAccountIdRoute
  '/(onboarding)/onboarding/setup': typeof onboardingOnboardingSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgotten-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/two-factor'
    | '/accounts'
    | '/categories'
    | '/dashboard'
    | '/organization'
    | '/settings'
    | '/transactions'
    | '/accept-invitation'
    | '/onboarding'
    | '/credit-cards/$accountId'
    | '/onboarding/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgotten-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/two-factor'
    | '/accounts'
    | '/categories'
    | '/dashboard'
    | '/organization'
    | '/settings'
    | '/transactions'
    | '/accept-invitation'
    | '/onboarding'
    | '/credit-cards/$accountId'
    | '/onboarding/setup'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(authenticated)'
    | '/(onboarding)'
    | '/(auth)/forgotten-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/sign-up'
    | '/(auth)/two-factor'
    | '/(authenticated)/accounts'
    | '/(authenticated)/categories'
    | '/(authenticated)/dashboard'
    | '/(authenticated)/organization'
    | '/(authenticated)/settings'
    | '/(authenticated)/transactions'
    | '/(onboarding)/accept-invitation'
    | '/(onboarding)/onboarding'
    | '/(authenticated)/credit-cards/$accountId'
    | '/(onboarding)/onboarding/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  onboardingRouteRoute: typeof onboardingRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(onboarding)': {
      id: '/(onboarding)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof onboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgotten-password': {
      id: '/(auth)/forgotten-password'
      path: '/forgotten-password'
      fullPath: '/forgotten-password'
      preLoaderRoute: typeof authForgottenPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/two-factor': {
      id: '/(auth)/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof authTwoFactorRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(authenticated)/accounts': {
      id: '/(authenticated)/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof authenticatedAccountsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/categories': {
      id: '/(authenticated)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof authenticatedCategoriesRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/organization': {
      id: '/(authenticated)/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof authenticatedOrganizationRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/settings': {
      id: '/(authenticated)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authenticatedSettingsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/transactions': {
      id: '/(authenticated)/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof authenticatedTransactionsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(onboarding)/accept-invitation': {
      id: '/(onboarding)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof onboardingAcceptInvitationRouteImport
      parentRoute: typeof onboardingRouteRoute
    }
    '/(onboarding)/onboarding': {
      id: '/(onboarding)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof onboardingOnboardingRouteImport
      parentRoute: typeof onboardingRouteRoute
    }
    '/(authenticated)/credit-cards/$accountId': {
      id: '/(authenticated)/credit-cards/$accountId'
      path: '/credit-cards/$accountId'
      fullPath: '/credit-cards/$accountId'
      preLoaderRoute: typeof authenticatedCreditCardsAccountIdRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(onboarding)/onboarding/setup': {
      id: '/(onboarding)/onboarding/setup'
      path: '/setup'
      fullPath: '/onboarding/setup'
      preLoaderRoute: typeof onboardingOnboardingSetupRouteImport
      parentRoute: typeof onboardingOnboardingRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgottenPasswordRoute: typeof authForgottenPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignUpRoute: typeof authSignUpRoute
  authTwoFactorRoute: typeof authTwoFactorRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgottenPasswordRoute: authForgottenPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignUpRoute: authSignUpRoute,
  authTwoFactorRoute: authTwoFactorRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface authenticatedRouteRouteChildren {
  authenticatedAccountsRoute: typeof authenticatedAccountsRoute
  authenticatedCategoriesRoute: typeof authenticatedCategoriesRoute
  authenticatedDashboardRoute: typeof authenticatedDashboardRoute
  authenticatedOrganizationRoute: typeof authenticatedOrganizationRoute
  authenticatedSettingsRoute: typeof authenticatedSettingsRoute
  authenticatedTransactionsRoute: typeof authenticatedTransactionsRoute
  authenticatedCreditCardsAccountIdRoute: typeof authenticatedCreditCardsAccountIdRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedAccountsRoute: authenticatedAccountsRoute,
  authenticatedCategoriesRoute: authenticatedCategoriesRoute,
  authenticatedDashboardRoute: authenticatedDashboardRoute,
  authenticatedOrganizationRoute: authenticatedOrganizationRoute,
  authenticatedSettingsRoute: authenticatedSettingsRoute,
  authenticatedTransactionsRoute: authenticatedTransactionsRoute,
  authenticatedCreditCardsAccountIdRoute:
    authenticatedCreditCardsAccountIdRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface onboardingOnboardingRouteChildren {
  onboardingOnboardingSetupRoute: typeof onboardingOnboardingSetupRoute
}

const onboardingOnboardingRouteChildren: onboardingOnboardingRouteChildren = {
  onboardingOnboardingSetupRoute: onboardingOnboardingSetupRoute,
}

const onboardingOnboardingRouteWithChildren =
  onboardingOnboardingRoute._addFileChildren(onboardingOnboardingRouteChildren)

interface onboardingRouteRouteChildren {
  onboardingAcceptInvitationRoute: typeof onboardingAcceptInvitationRoute
  onboardingOnboardingRoute: typeof onboardingOnboardingRouteWithChildren
}

const onboardingRouteRouteChildren: onboardingRouteRouteChildren = {
  onboardingAcceptInvitationRoute: onboardingAcceptInvitationRoute,
  onboardingOnboardingRoute: onboardingOnboardingRouteWithChildren,
}

const onboardingRouteRouteWithChildren = onboardingRouteRoute._addFileChildren(
  onboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  onboardingRouteRoute: onboardingRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
